import os
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

class PDFReportGenerator:
    def __init__(self):
        pass

    def generate_pdf(self, session_data: dict, output_path: str) -> str:
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36
        )

        styles = getSampleStyleSheet()
        
        # Custom Styles
        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Heading1'],
            fontSize=22,
            leading=26,
            textColor=colors.HexColor('#1E1B4B'),
            fontName='Helvetica-Bold'
        )
        subtitle_style = ParagraphStyle(
            'DocSubTitle',
            parent=styles['Normal'],
            fontSize=11,
            leading=14,
            textColor=colors.HexColor('#4B5563')
        )
        h2_style = ParagraphStyle(
            'Heading2Custom',
            parent=styles['Heading2'],
            fontSize=14,
            leading=18,
            textColor=colors.HexColor('#312E81'),
            spaceBefore=12,
            spaceAfter=6,
            fontName='Helvetica-Bold'
        )
        body_style = ParagraphStyle(
            'BodyCustom',
            parent=styles['Normal'],
            fontSize=9,
            leading=12,
            textColor=colors.HexColor('#1F2937')
        )

        story = []

        # Title Block
        story.append(Paragraph("TECHNICAL DIAGRAM ANOMALY & SELF-HEALING REPORT", title_style))
        story.append(Spacer(1, 4))
        story.append(Paragraph("Generated by Error-Aware VQA & Self-Healing AI Platform | Final Year B.Tech Project", subtitle_style))
        story.append(Spacer(1, 10))
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#6366F1'), spaceBefore=4, spaceAfter=12))

        # Executive Summary Box
        summary = session_data.get("summary", {})
        graph = session_data.get("graph", {})
        val = session_data.get("validation", {})
        anoms = session_data.get("anomalies", [])

        summary_data = [
            [Paragraph("<b>Diagram Type:</b>", body_style), Paragraph(str(summary.get("diagram_type", "Flowchart")), body_style),
             Paragraph("<b>Processing Time:</b>", body_style), Paragraph(f"{summary.get('processing_time', 0.45)} s", body_style)],
            [Paragraph("<b>Detected Symbols:</b>", body_style), Paragraph(str(summary.get("total_symbols", 0)), body_style),
             Paragraph("<b>Detected Text Segments:</b>", body_style), Paragraph(str(summary.get("total_text_segments", 0)), body_style)],
            [Paragraph("<b>Validation Status:</b>", body_style), 
             Paragraph(f"<font color='{'red' if not val.get('is_valid') else 'green'}'><b>{'ANOMALIES DETECTED' if not val.get('is_valid') else 'VALID'}</b></font>", body_style),
             Paragraph("<b>Total Errors Found:</b>", body_style), Paragraph(str(val.get("total_errors", 0)), body_style)]
        ]

        t_summary = Table(summary_data, colWidths=[120, 150, 120, 150])
        t_summary.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F3F4F6')),
            ('PADDING', (0,0), (-1,-1), 6),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E5E7EB')),
        ]))
        story.append(t_summary)
        story.append(Spacer(1, 14))

        # Section 1: Detected Objects & OCR
        story.append(Paragraph("1. Detected Symbol & OCR Extraction Matrix", h2_style))
        ocr_list = session_data.get("ocr", [])
        ocr_table_data = [["Node ID", "Shape Symbol", "Extracted Label / Text", "Confidence"]]

        for item in ocr_list[:8]:
            ocr_table_data.append([
                str(item.get("node_id")),
                str(item.get("shape")),
                str(item.get("text")),
                f"{item.get('confidence', 0.90)*100:.1f}%"
            ])

        t_ocr = Table(ocr_table_data, colWidths=[80, 120, 240, 100])
        t_ocr.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#4338CA')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
            ('PADDING', (0,0), (-1,-1), 5),
        ]))
        story.append(t_ocr)
        story.append(Spacer(1, 14))

        # Section 2: Anomaly Diagnostic Report
        story.append(Paragraph("2. Anomaly Reasoning & Self-Healing Log", h2_style))
        anom_table_data = [["ID", "Anomaly Code", "Severity", "Reasoning & Suggested Repair"]]

        for a in anoms:
            anom_table_data.append([
                str(a.get("id")),
                str(a.get("code")),
                str(a.get("severity")),
                Paragraph(f"<b>Reason:</b> {a.get('reason')}<br/><b>Repair:</b> {a.get('suggested_repair')}", body_style)
            ])

        if len(anom_table_data) > 1:
            t_anom = Table(anom_table_data, colWidths=[60, 110, 80, 290])
            t_anom.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#DC2626')),
                ('TEXTCOLOR', (0,0), (-1,0), colors.white),
                ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#FECACA')),
                ('PADDING', (0,0), (-1,-1), 5),
            ]))
            story.append(t_anom)
        else:
            story.append(Paragraph("No anomalies detected.", body_style))

        story.append(Spacer(1, 14))

        # Section 3: Visual Question Answering Log
        vqa_list = session_data.get("vqa_history", [])
        if vqa_list:
            story.append(Paragraph("3. Visual Question Answering Interaction Log", h2_style))
            vqa_table_data = [["Question", "AI Answer", "Confidence"]]
            for v in vqa_list:
                vqa_table_data.append([
                    Paragraph(v.get("question", ""), body_style),
                    Paragraph(v.get("answer", ""), body_style),
                    f"{v.get('confidence', 0.95)*100:.1f}%"
                ])
            t_vqa = Table(vqa_table_data, colWidths=[180, 280, 80])
            t_vqa.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#0284C7')),
                ('TEXTCOLOR', (0,0), (-1,0), colors.white),
                ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#BAE6FD')),
                ('PADDING', (0,0), (-1,-1), 5),
            ]))
            story.append(t_vqa)

        doc.build(story)
        return output_path
